//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minesweeper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int Id { get; set; }
        public string player { get; set; }
        public int rows { get; set; }
        public int columns { get; set; }
        public int bombs_percentage { get; set; }
        public int seconds { get; set; }
        public int clicks { get; set; }
    }
}
